export const data = [
  {
    Name: "Hey Man Nice Shot",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Jurassitol",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Trip Like I Do",
    Guitar: "D",
    Bass: "C",
    Duration: "4:00",
  },
  {
    Name: "Take a Picture",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Hey Man Nice Shot",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Welcome to the Fold",
    Guitar: "A",
    Bass: "A",
    Duration: "4:00",
  },
  {
    Name: "Trip Like I Do",
    Guitar: "D",
    Bass: "C",
    Duration: "4:00",
  },
  {
    Name: "Take a Picture",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Hey Man Nice Shot",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Jurassitol",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Trip Like I Do",
    Guitar: "D",
    Bass: "C",
    Duration: "4:00",
  },
  {
    Name: "Take a Picture",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Hey Man Nice Shot",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Jurassitol",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
  {
    Name: "Trip Like I Do",
    Guitar: "D",
    Bass: "C",
    Duration: "4:00",
  },
  {
    Name: "Take a Picture",
    Guitar: "D",
    Bass: "D",
    Duration: "4:00",
  },
];
